name: "Publish Release"

on:
  push:
    branches:
      - ejecutable # Se activa automáticamente cada vez que haces push a la rama 'ejecutable'

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install frontend dependencies
        run: npm ci

      - name: Build and Publish with Tauri Action
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__ # tauri-action reemplaza __VERSION__ con la versión en tauri.conf.json
          releaseName: "Pixel Tanks v__VERSION__"
          releaseBody: "Ejecutables oficiales para la versión v__VERSION__. Descarga el archivo correspondiente a tu sistema operativo."
          releaseDraft: true # Crea la versión como Borrador (Draft) para que puedas revisarla antes de publicarla
          prerelease: false
          args: ${{ matrix.args }}
